build: off

environment:
  nodejs_version: "7.4.0"

install:
  - git submodule update --init --recursive
  - git clone https://github.com/stream-labs/node-obs-prebuild.git node-obs
  - yarn install
  - yarn ci:compile

test_script:
  - yarn test -- -v
